---

name: Checks

### So we're saying we want this particular GitHub actions to run on push, which means any push of changes to our project.
##So any time we do get comment and then push it up to GitHub, it's going to run the jobs that we specify
##inside this text YAML file.
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 ##Runs on is the runner that we're going to be running our job on.
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: docker-compose run --rm app sh -c "python manage.py test"
    - name: Lint
      run: docker-compose run --rm app sh -c "flake8"